### ISSUE TITLE
Minimise `zcashd` files pulled in by `zcash_script` 

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3041]
## Motivation

`zcash_script` is only used for transparent script validation.

If we pull in more dependencies than we need, builds are slower. They also become more fragile, because our test platforms are not the same as `zcashd`. (For example, Zebra builds with `MSVC` on Windows, but `zcashd` cross-compiles to Windows.)

### Suggestions

The following crates should not be required for transparent script validation, unless they are used for transaction serialization:
```toml
halo2 = "0.1.0-beta.1"
incrementalmerkletree = "0.1"
zcash_note_encryption = "0.0"
```

Similarly, the following Rust modules should not be required:
```rust
mod ed25519;

mod history_ffi;
mod orchard_ffi::incremental_sinsemilla_tree_ffi;
mod zip339_ffi;

mod test_harness_ffi;
```
