### ISSUE TITLE
ci: check if the actual paths being used by the full sync test needs improvement

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#4091]
## Motivation

All PRs that change a Rust file `*.rs` are being testes with a full sync, maybe there are scenarios were this is not needed.

```yaml
name: Full sync test

on:
  workflow_dispatch:
    inputs:
      network:
        default: 'Mainnet'
  pull_request:
    branches:
      - main
    paths:
      # code and tests (including full sync acceptance test changes)
      # TODO: ignore changes in test code that isn't used in the full sync test
      - '**/*.rs'
      # hard-coded checkpoints
      # TODO: ignore changes to proptest seed .txt files
      - '**/*.txt'
      # dependencies
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      # workflow definitions
      - 'docker/**'
      - '.github/workflows/test-full-sync.yml'
```

### Designs

- Add a `paths-ignore` to add exceptions to this workflow
