### ISSUE TITLE
Add a GitHub action that detects unused dependencies

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6215]
## Motivation

We want to remove unused dependencies to improve Zebra's security, by reducing the amount of code we compile and run. This also makes builds faster, binaries smaller, and reduces or maintenance load.

### Specifications

[cargo-machete](https://github.com/bnjbvr/cargo-machete) should work, but we might want to use no default features, default features, and all features:
machete:
 ```
runs-on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v3
       - name: install toolchain
          …
       - name: Install cargo-machete
         uses: baptiste0928/cargo-install@v1
         with:
           crate: cargo-machete
       - name: Check unused dependencies
         run: cargo machete
```

### Complex Code or Requirements

We need to make sure we don't remove dependencies that are only used by some features.

### Testing

We should make this a required CI job in the branch protection rules, and add a patch job for it.
